// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LinkItem is the predicate function for linkitem builders.
type LinkItem func(*sql.Selector)

// Page is the predicate function for page builders.
type Page func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
