// Code generated by MockGen. DO NOT EDIT.
// Source: ./list.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_list/list.go -source=./list.go -package=mocklistusecase
//

// Package mocklistusecase is a generated GoMock package.
package mocklistusecase

import (
	context "context"
	reflect "reflect"

	page "github.com/naka-sei/tsudzuri/domain/page"
	gomock "go.uber.org/mock/gomock"
)

// MockListUsecase is a mock of ListUsecase interface.
type MockListUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockListUsecaseMockRecorder
	isgomock struct{}
}

// MockListUsecaseMockRecorder is the mock recorder for MockListUsecase.
type MockListUsecaseMockRecorder struct {
	mock *MockListUsecase
}

// NewMockListUsecase creates a new mock instance.
func NewMockListUsecase(ctrl *gomock.Controller) *MockListUsecase {
	mock := &MockListUsecase{ctrl: ctrl}
	mock.recorder = &MockListUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListUsecase) EXPECT() *MockListUsecaseMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockListUsecase) List(ctx context.Context, options ...page.SearchOption) ([]*page.Page, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*page.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockListUsecaseMockRecorder) List(ctx any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockListUsecase)(nil).List), varargs...)
}
