// Code generated by MockGen. DO NOT EDIT.
// Source: ./get.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_get/get.go -source=./get.go -package=mockgetusecase
//

// Package mockgetusecase is a generated GoMock package.
package mockgetusecase

import (
	context "context"
	reflect "reflect"

	page "github.com/naka-sei/tsudzuri/domain/page"
	gomock "go.uber.org/mock/gomock"
)

// MockGetUsecase is a mock of GetUsecase interface.
type MockGetUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetUsecaseMockRecorder
	isgomock struct{}
}

// MockGetUsecaseMockRecorder is the mock recorder for MockGetUsecase.
type MockGetUsecaseMockRecorder struct {
	mock *MockGetUsecase
}

// NewMockGetUsecase creates a new mock instance.
func NewMockGetUsecase(ctrl *gomock.Controller) *MockGetUsecase {
	mock := &MockGetUsecase{ctrl: ctrl}
	mock.recorder = &MockGetUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUsecase) EXPECT() *MockGetUsecaseMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGetUsecase) Get(ctx context.Context, pageID string) (*page.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, pageID)
	ret0, _ := ret[0].(*page.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGetUsecaseMockRecorder) Get(ctx, pageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGetUsecase)(nil).Get), ctx, pageID)
}
