// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_page/page.go -source=./repository.go -package=mockpage
//

// Package mockpage is a generated GoMock package.
package mockpage

import (
	reflect "reflect"

	page "github.com/naka-sei/tsudzuri/domain/page"
	gomock "go.uber.org/mock/gomock"
)

// MockPageRepository is a mock of PageRepository interface.
type MockPageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPageRepositoryMockRecorder
	isgomock struct{}
}

// MockPageRepositoryMockRecorder is the mock recorder for MockPageRepository.
type MockPageRepositoryMockRecorder struct {
	mock *MockPageRepository
}

// NewMockPageRepository creates a new mock instance.
func NewMockPageRepository(ctrl *gomock.Controller) *MockPageRepository {
	mock := &MockPageRepository{ctrl: ctrl}
	mock.recorder = &MockPageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPageRepository) EXPECT() *MockPageRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockPageRepository) FindByID(id int64) (*page.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*page.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPageRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPageRepository)(nil).FindByID), id)
}

// Save mocks base method.
func (m *MockPageRepository) Save(arg0 *page.Page) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPageRepositoryMockRecorder) Save(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPageRepository)(nil).Save), arg0)
}
