// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: tsudzuri/v1/tsudzuri.proto

package tsudzuriv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	InviteCode    string                 `protobuf:"bytes,3,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	Links         []*Link                `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *Page) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Memo          string                 `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Link) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Link) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type CreatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageRequest) Reset() {
	*x = CreatePageRequest{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageRequest) ProtoMessage() {}

func (x *CreatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageRequest.ProtoReflect.Descriptor instead.
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageRequest) Reset() {
	*x = GetPageRequest{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageRequest) ProtoMessage() {}

func (x *GetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageRequest.ProtoReflect.Descriptor instead.
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{3}
}

func (x *GetPageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type ListPagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesRequest) Reset() {
	*x = ListPagesRequest{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesRequest) ProtoMessage() {}

func (x *ListPagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesRequest.ProtoReflect.Descriptor instead.
func (*ListPagesRequest) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{4}
}

type ListPagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*Page                `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesResponse) Reset() {
	*x = ListPagesResponse{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesResponse) ProtoMessage() {}

func (x *ListPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesResponse.ProtoReflect.Descriptor instead.
func (*ListPagesResponse) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{5}
}

func (x *ListPagesResponse) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

type EditPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Links         []*LinkInput           `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPageRequest) Reset() {
	*x = EditPageRequest{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPageRequest) ProtoMessage() {}

func (x *EditPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPageRequest.ProtoReflect.Descriptor instead.
func (*EditPageRequest) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{6}
}

func (x *EditPageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *EditPageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditPageRequest) GetLinks() []*LinkInput {
	if x != nil {
		return x.Links
	}
	return nil
}

type LinkInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Memo          string                 `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkInput) Reset() {
	*x = LinkInput{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkInput) ProtoMessage() {}

func (x *LinkInput) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkInput.ProtoReflect.Descriptor instead.
func (*LinkInput) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{7}
}

func (x *LinkInput) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LinkInput) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *LinkInput) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type DeletePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePageRequest) Reset() {
	*x = DeletePageRequest{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePageRequest) ProtoMessage() {}

func (x *DeletePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePageRequest.ProtoReflect.Descriptor instead.
func (*DeletePageRequest) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type AddLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Memo          string                 `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinkRequest) Reset() {
	*x = AddLinkRequest{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinkRequest) ProtoMessage() {}

func (x *AddLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinkRequest.ProtoReflect.Descriptor instead.
func (*AddLinkRequest) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{9}
}

func (x *AddLinkRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *AddLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddLinkRequest) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

type RemoveLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLinkRequest) Reset() {
	*x = RemoveLinkRequest{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLinkRequest) ProtoMessage() {}

func (x *RemoveLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLinkRequest.ProtoReflect.Descriptor instead.
func (*RemoveLinkRequest) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveLinkRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *RemoveLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type JoinPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	InviteCode    string                 `protobuf:"bytes,2,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPageRequest) Reset() {
	*x = JoinPageRequest{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPageRequest) ProtoMessage() {}

func (x *JoinPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPageRequest.ProtoReflect.Descriptor instead.
func (*JoinPageRequest) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{11}
}

func (x *JoinPageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *JoinPageRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{12}
}

func (x *CreateUserRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           string                  `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Provider      string                  `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Email         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	JoinedPageIds []string                `protobuf:"bytes,5,rep,name=joined_page_ids,json=joinedPageIds,proto3" json:"joined_page_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{13}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *User) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *User) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *User) GetJoinedPageIds() []string {
	if x != nil {
		return x.JoinedPageIds
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Provider      string                  `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Email         *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsudzuri_v1_tsudzuri_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP(), []int{14}
}

func (x *LoginRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LoginRequest) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

var File_tsudzuri_v1_tsudzuri_proto protoreflect.FileDescriptor

const file_tsudzuri_v1_tsudzuri_proto_rawDesc = "" +
	"\n" +
	"\x1atsudzuri/v1/tsudzuri.proto\x12\vtsudzuri.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"v\n" +
	"\x04Page\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vinvite_code\x18\x03 \x01(\tR\n" +
	"inviteCode\x12'\n" +
	"\x05links\x18\x04 \x03(\v2\x11.tsudzuri.v1.LinkR\x05links\"H\n" +
	"\x04Link\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04memo\x18\x02 \x01(\tR\x04memo\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\")\n" +
	"\x11CreatePageRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\")\n" +
	"\x0eGetPageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"\x12\n" +
	"\x10ListPagesRequest\"<\n" +
	"\x11ListPagesResponse\x12'\n" +
	"\x05pages\x18\x01 \x03(\v2\x11.tsudzuri.v1.PageR\x05pages\"n\n" +
	"\x0fEditPageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12,\n" +
	"\x05links\x18\x03 \x03(\v2\x16.tsudzuri.v1.LinkInputR\x05links\"M\n" +
	"\tLinkInput\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04memo\x18\x02 \x01(\tR\x04memo\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\",\n" +
	"\x11DeletePageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"O\n" +
	"\x0eAddLinkRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04memo\x18\x03 \x01(\tR\x04memo\">\n" +
	"\x11RemoveLinkRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"K\n" +
	"\x0fJoinPageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1f\n" +
	"\vinvite_code\x18\x02 \x01(\tR\n" +
	"inviteCode\"%\n" +
	"\x11CreateUserRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"\xa0\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x122\n" +
	"\x05email\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05email\x12&\n" +
	"\x0fjoined_page_ids\x18\x05 \x03(\tR\rjoinedPageIds\"^\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x122\n" +
	"\x05email\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05email2\xc2\b\n" +
	"\x0fTsudzuriService\x12^\n" +
	"\n" +
	"CreatePage\x12\x1e.tsudzuri.v1.CreatePageRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/pages\x12Z\n" +
	"\aGetPage\x12\x1b.tsudzuri.v1.GetPageRequest\x1a\x11.tsudzuri.v1.Page\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/pages/{page_id}\x12a\n" +
	"\tListPages\x12\x1d.tsudzuri.v1.ListPagesRequest\x1a\x1e.tsudzuri.v1.ListPagesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/pages\x12d\n" +
	"\bEditPage\x12\x1c.tsudzuri.v1.EditPageRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/v1/pages/{page_id}\x12e\n" +
	"\n" +
	"DeletePage\x12\x1e.tsudzuri.v1.DeletePageRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/v1/pages/{page_id}\x12h\n" +
	"\aAddLink\x12\x1b.tsudzuri.v1.AddLinkRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/pages/{page_id}/links\x12k\n" +
	"\n" +
	"RemoveLink\x12\x1e.tsudzuri.v1.RemoveLinkRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/api/v1/pages/{page_id}/links\x12i\n" +
	"\bJoinPage\x12\x1c.tsudzuri.v1.JoinPageRequest\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/pages/{page_id}/join\x12Y\n" +
	"\n" +
	"CreateUser\x12\x1e.tsudzuri.v1.CreateUserRequest\x1a\x11.tsudzuri.v1.User\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12Z\n" +
	"\x05Login\x12\x19.tsudzuri.v1.LoginRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/users/login\x12J\n" +
	"\x03Get\x12\x16.google.protobuf.Empty\x1a\x11.tsudzuri.v1.User\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/users/meB\xaf\x01\n" +
	"\x0fcom.tsudzuri.v1B\rTsudzuriProtoP\x01Z@github.com/naka-sei/tsudzuri/api/protobuf/tsudzuri/v1;tsudzuriv1\xa2\x02\x03TXX\xaa\x02\vTsudzuri.V1\xca\x02\vTsudzuri\\V1\xe2\x02\x17Tsudzuri\\V1\\GPBMetadata\xea\x02\fTsudzuri::V1b\x06proto3"

var (
	file_tsudzuri_v1_tsudzuri_proto_rawDescOnce sync.Once
	file_tsudzuri_v1_tsudzuri_proto_rawDescData []byte
)

func file_tsudzuri_v1_tsudzuri_proto_rawDescGZIP() []byte {
	file_tsudzuri_v1_tsudzuri_proto_rawDescOnce.Do(func() {
		file_tsudzuri_v1_tsudzuri_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tsudzuri_v1_tsudzuri_proto_rawDesc), len(file_tsudzuri_v1_tsudzuri_proto_rawDesc)))
	})
	return file_tsudzuri_v1_tsudzuri_proto_rawDescData
}

var file_tsudzuri_v1_tsudzuri_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_tsudzuri_v1_tsudzuri_proto_goTypes = []any{
	(*Page)(nil),                   // 0: tsudzuri.v1.Page
	(*Link)(nil),                   // 1: tsudzuri.v1.Link
	(*CreatePageRequest)(nil),      // 2: tsudzuri.v1.CreatePageRequest
	(*GetPageRequest)(nil),         // 3: tsudzuri.v1.GetPageRequest
	(*ListPagesRequest)(nil),       // 4: tsudzuri.v1.ListPagesRequest
	(*ListPagesResponse)(nil),      // 5: tsudzuri.v1.ListPagesResponse
	(*EditPageRequest)(nil),        // 6: tsudzuri.v1.EditPageRequest
	(*LinkInput)(nil),              // 7: tsudzuri.v1.LinkInput
	(*DeletePageRequest)(nil),      // 8: tsudzuri.v1.DeletePageRequest
	(*AddLinkRequest)(nil),         // 9: tsudzuri.v1.AddLinkRequest
	(*RemoveLinkRequest)(nil),      // 10: tsudzuri.v1.RemoveLinkRequest
	(*JoinPageRequest)(nil),        // 11: tsudzuri.v1.JoinPageRequest
	(*CreateUserRequest)(nil),      // 12: tsudzuri.v1.CreateUserRequest
	(*User)(nil),                   // 13: tsudzuri.v1.User
	(*LoginRequest)(nil),           // 14: tsudzuri.v1.LoginRequest
	(*wrapperspb.StringValue)(nil), // 15: google.protobuf.StringValue
	(*emptypb.Empty)(nil),          // 16: google.protobuf.Empty
}
var file_tsudzuri_v1_tsudzuri_proto_depIdxs = []int32{
	1,  // 0: tsudzuri.v1.Page.links:type_name -> tsudzuri.v1.Link
	0,  // 1: tsudzuri.v1.ListPagesResponse.pages:type_name -> tsudzuri.v1.Page
	7,  // 2: tsudzuri.v1.EditPageRequest.links:type_name -> tsudzuri.v1.LinkInput
	15, // 3: tsudzuri.v1.User.email:type_name -> google.protobuf.StringValue
	15, // 4: tsudzuri.v1.LoginRequest.email:type_name -> google.protobuf.StringValue
	2,  // 5: tsudzuri.v1.TsudzuriService.CreatePage:input_type -> tsudzuri.v1.CreatePageRequest
	3,  // 6: tsudzuri.v1.TsudzuriService.GetPage:input_type -> tsudzuri.v1.GetPageRequest
	4,  // 7: tsudzuri.v1.TsudzuriService.ListPages:input_type -> tsudzuri.v1.ListPagesRequest
	6,  // 8: tsudzuri.v1.TsudzuriService.EditPage:input_type -> tsudzuri.v1.EditPageRequest
	8,  // 9: tsudzuri.v1.TsudzuriService.DeletePage:input_type -> tsudzuri.v1.DeletePageRequest
	9,  // 10: tsudzuri.v1.TsudzuriService.AddLink:input_type -> tsudzuri.v1.AddLinkRequest
	10, // 11: tsudzuri.v1.TsudzuriService.RemoveLink:input_type -> tsudzuri.v1.RemoveLinkRequest
	11, // 12: tsudzuri.v1.TsudzuriService.JoinPage:input_type -> tsudzuri.v1.JoinPageRequest
	12, // 13: tsudzuri.v1.TsudzuriService.CreateUser:input_type -> tsudzuri.v1.CreateUserRequest
	14, // 14: tsudzuri.v1.TsudzuriService.Login:input_type -> tsudzuri.v1.LoginRequest
	16, // 15: tsudzuri.v1.TsudzuriService.Get:input_type -> google.protobuf.Empty
	16, // 16: tsudzuri.v1.TsudzuriService.CreatePage:output_type -> google.protobuf.Empty
	0,  // 17: tsudzuri.v1.TsudzuriService.GetPage:output_type -> tsudzuri.v1.Page
	5,  // 18: tsudzuri.v1.TsudzuriService.ListPages:output_type -> tsudzuri.v1.ListPagesResponse
	16, // 19: tsudzuri.v1.TsudzuriService.EditPage:output_type -> google.protobuf.Empty
	16, // 20: tsudzuri.v1.TsudzuriService.DeletePage:output_type -> google.protobuf.Empty
	16, // 21: tsudzuri.v1.TsudzuriService.AddLink:output_type -> google.protobuf.Empty
	16, // 22: tsudzuri.v1.TsudzuriService.RemoveLink:output_type -> google.protobuf.Empty
	16, // 23: tsudzuri.v1.TsudzuriService.JoinPage:output_type -> google.protobuf.Empty
	13, // 24: tsudzuri.v1.TsudzuriService.CreateUser:output_type -> tsudzuri.v1.User
	16, // 25: tsudzuri.v1.TsudzuriService.Login:output_type -> google.protobuf.Empty
	13, // 26: tsudzuri.v1.TsudzuriService.Get:output_type -> tsudzuri.v1.User
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tsudzuri_v1_tsudzuri_proto_init() }
func file_tsudzuri_v1_tsudzuri_proto_init() {
	if File_tsudzuri_v1_tsudzuri_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tsudzuri_v1_tsudzuri_proto_rawDesc), len(file_tsudzuri_v1_tsudzuri_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tsudzuri_v1_tsudzuri_proto_goTypes,
		DependencyIndexes: file_tsudzuri_v1_tsudzuri_proto_depIdxs,
		MessageInfos:      file_tsudzuri_v1_tsudzuri_proto_msgTypes,
	}.Build()
	File_tsudzuri_v1_tsudzuri_proto = out.File
	file_tsudzuri_v1_tsudzuri_proto_goTypes = nil
	file_tsudzuri_v1_tsudzuri_proto_depIdxs = nil
}
