// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: tsudzuri/v1/tsudzuri.proto

package tsudzuriv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TsudzuriService_CreatePage_FullMethodName = "/tsudzuri.v1.TsudzuriService/CreatePage"
	TsudzuriService_GetPage_FullMethodName    = "/tsudzuri.v1.TsudzuriService/GetPage"
	TsudzuriService_ListPages_FullMethodName  = "/tsudzuri.v1.TsudzuriService/ListPages"
	TsudzuriService_EditPage_FullMethodName   = "/tsudzuri.v1.TsudzuriService/EditPage"
	TsudzuriService_DeletePage_FullMethodName = "/tsudzuri.v1.TsudzuriService/DeletePage"
	TsudzuriService_AddLink_FullMethodName    = "/tsudzuri.v1.TsudzuriService/AddLink"
	TsudzuriService_RemoveLink_FullMethodName = "/tsudzuri.v1.TsudzuriService/RemoveLink"
	TsudzuriService_JoinPage_FullMethodName   = "/tsudzuri.v1.TsudzuriService/JoinPage"
	TsudzuriService_CreateUser_FullMethodName = "/tsudzuri.v1.TsudzuriService/CreateUser"
	TsudzuriService_Login_FullMethodName      = "/tsudzuri.v1.TsudzuriService/Login"
	TsudzuriService_Get_FullMethodName        = "/tsudzuri.v1.TsudzuriService/Get"
)

// TsudzuriServiceClient is the client API for TsudzuriService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TsudzuriServiceClient interface {
	// Page management
	CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*Page, error)
	ListPages(ctx context.Context, in *ListPagesRequest, opts ...grpc.CallOption) (*ListPagesResponse, error)
	EditPage(ctx context.Context, in *EditPageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeletePage(ctx context.Context, in *DeletePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddLink(ctx context.Context, in *AddLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveLink(ctx context.Context, in *RemoveLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	JoinPage(ctx context.Context, in *JoinPageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// User management
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*User, error)
}

type tsudzuriServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTsudzuriServiceClient(cc grpc.ClientConnInterface) TsudzuriServiceClient {
	return &tsudzuriServiceClient{cc}
}

func (c *tsudzuriServiceClient) CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TsudzuriService_CreatePage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsudzuriServiceClient) GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := c.cc.Invoke(ctx, TsudzuriService_GetPage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsudzuriServiceClient) ListPages(ctx context.Context, in *ListPagesRequest, opts ...grpc.CallOption) (*ListPagesResponse, error) {
	out := new(ListPagesResponse)
	err := c.cc.Invoke(ctx, TsudzuriService_ListPages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsudzuriServiceClient) EditPage(ctx context.Context, in *EditPageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TsudzuriService_EditPage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsudzuriServiceClient) DeletePage(ctx context.Context, in *DeletePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TsudzuriService_DeletePage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsudzuriServiceClient) AddLink(ctx context.Context, in *AddLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TsudzuriService_AddLink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsudzuriServiceClient) RemoveLink(ctx context.Context, in *RemoveLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TsudzuriService_RemoveLink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsudzuriServiceClient) JoinPage(ctx context.Context, in *JoinPageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TsudzuriService_JoinPage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsudzuriServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, TsudzuriService_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsudzuriServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TsudzuriService_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsudzuriServiceClient) Get(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, TsudzuriService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TsudzuriServiceServer is the server API for TsudzuriService service.
// All implementations must embed UnimplementedTsudzuriServiceServer
// for forward compatibility
type TsudzuriServiceServer interface {
	// Page management
	CreatePage(context.Context, *CreatePageRequest) (*emptypb.Empty, error)
	GetPage(context.Context, *GetPageRequest) (*Page, error)
	ListPages(context.Context, *ListPagesRequest) (*ListPagesResponse, error)
	EditPage(context.Context, *EditPageRequest) (*emptypb.Empty, error)
	DeletePage(context.Context, *DeletePageRequest) (*emptypb.Empty, error)
	AddLink(context.Context, *AddLinkRequest) (*emptypb.Empty, error)
	RemoveLink(context.Context, *RemoveLinkRequest) (*emptypb.Empty, error)
	JoinPage(context.Context, *JoinPageRequest) (*emptypb.Empty, error)
	// User management
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	Login(context.Context, *LoginRequest) (*emptypb.Empty, error)
	Get(context.Context, *emptypb.Empty) (*User, error)
	mustEmbedUnimplementedTsudzuriServiceServer()
}

// UnimplementedTsudzuriServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTsudzuriServiceServer struct {
}

func (UnimplementedTsudzuriServiceServer) CreatePage(context.Context, *CreatePageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePage not implemented")
}
func (UnimplementedTsudzuriServiceServer) GetPage(context.Context, *GetPageRequest) (*Page, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (UnimplementedTsudzuriServiceServer) ListPages(context.Context, *ListPagesRequest) (*ListPagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPages not implemented")
}
func (UnimplementedTsudzuriServiceServer) EditPage(context.Context, *EditPageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditPage not implemented")
}
func (UnimplementedTsudzuriServiceServer) DeletePage(context.Context, *DeletePageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePage not implemented")
}
func (UnimplementedTsudzuriServiceServer) AddLink(context.Context, *AddLinkRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLink not implemented")
}
func (UnimplementedTsudzuriServiceServer) RemoveLink(context.Context, *RemoveLinkRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLink not implemented")
}
func (UnimplementedTsudzuriServiceServer) JoinPage(context.Context, *JoinPageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinPage not implemented")
}
func (UnimplementedTsudzuriServiceServer) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedTsudzuriServiceServer) Login(context.Context, *LoginRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedTsudzuriServiceServer) Get(context.Context, *emptypb.Empty) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTsudzuriServiceServer) mustEmbedUnimplementedTsudzuriServiceServer() {}

// UnsafeTsudzuriServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TsudzuriServiceServer will
// result in compilation errors.
type UnsafeTsudzuriServiceServer interface {
	mustEmbedUnimplementedTsudzuriServiceServer()
}

func RegisterTsudzuriServiceServer(s grpc.ServiceRegistrar, srv TsudzuriServiceServer) {
	s.RegisterService(&TsudzuriService_ServiceDesc, srv)
}

func _TsudzuriService_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsudzuriServiceServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsudzuriService_CreatePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsudzuriServiceServer).CreatePage(ctx, req.(*CreatePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsudzuriService_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsudzuriServiceServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsudzuriService_GetPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsudzuriServiceServer).GetPage(ctx, req.(*GetPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsudzuriService_ListPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsudzuriServiceServer).ListPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsudzuriService_ListPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsudzuriServiceServer).ListPages(ctx, req.(*ListPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsudzuriService_EditPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsudzuriServiceServer).EditPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsudzuriService_EditPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsudzuriServiceServer).EditPage(ctx, req.(*EditPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsudzuriService_DeletePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsudzuriServiceServer).DeletePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsudzuriService_DeletePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsudzuriServiceServer).DeletePage(ctx, req.(*DeletePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsudzuriService_AddLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsudzuriServiceServer).AddLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsudzuriService_AddLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsudzuriServiceServer).AddLink(ctx, req.(*AddLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsudzuriService_RemoveLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsudzuriServiceServer).RemoveLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsudzuriService_RemoveLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsudzuriServiceServer).RemoveLink(ctx, req.(*RemoveLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsudzuriService_JoinPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsudzuriServiceServer).JoinPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsudzuriService_JoinPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsudzuriServiceServer).JoinPage(ctx, req.(*JoinPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsudzuriService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsudzuriServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsudzuriService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsudzuriServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsudzuriService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsudzuriServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsudzuriService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsudzuriServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TsudzuriService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsudzuriServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TsudzuriService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsudzuriServiceServer).Get(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TsudzuriService_ServiceDesc is the grpc.ServiceDesc for TsudzuriService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TsudzuriService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tsudzuri.v1.TsudzuriService",
	HandlerType: (*TsudzuriServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePage",
			Handler:    _TsudzuriService_CreatePage_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _TsudzuriService_GetPage_Handler,
		},
		{
			MethodName: "ListPages",
			Handler:    _TsudzuriService_ListPages_Handler,
		},
		{
			MethodName: "EditPage",
			Handler:    _TsudzuriService_EditPage_Handler,
		},
		{
			MethodName: "DeletePage",
			Handler:    _TsudzuriService_DeletePage_Handler,
		},
		{
			MethodName: "AddLink",
			Handler:    _TsudzuriService_AddLink_Handler,
		},
		{
			MethodName: "RemoveLink",
			Handler:    _TsudzuriService_RemoveLink_Handler,
		},
		{
			MethodName: "JoinPage",
			Handler:    _TsudzuriService_JoinPage_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _TsudzuriService_CreateUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _TsudzuriService_Login_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TsudzuriService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tsudzuri/v1/tsudzuri.proto",
}
