// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/linkitem"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/page"
)

// LinkItemCreate is the builder for creating a LinkItem entity.
type LinkItemCreate struct {
	config
	mutation *LinkItemMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LinkItemCreate) SetCreatedAt(v time.Time) *LinkItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LinkItemCreate) SetNillableCreatedAt(v *time.Time) *LinkItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LinkItemCreate) SetUpdatedAt(v time.Time) *LinkItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LinkItemCreate) SetNillableUpdatedAt(v *time.Time) *LinkItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPageID sets the "page_id" field.
func (_c *LinkItemCreate) SetPageID(v uuid.UUID) *LinkItemCreate {
	_c.mutation.SetPageID(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *LinkItemCreate) SetURL(v string) *LinkItemCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetMemo sets the "memo" field.
func (_c *LinkItemCreate) SetMemo(v string) *LinkItemCreate {
	_c.mutation.SetMemo(v)
	return _c
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_c *LinkItemCreate) SetNillableMemo(v *string) *LinkItemCreate {
	if v != nil {
		_c.SetMemo(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *LinkItemCreate) SetPriority(v int) *LinkItemCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *LinkItemCreate) SetNillablePriority(v *int) *LinkItemCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LinkItemCreate) SetID(v uuid.UUID) *LinkItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LinkItemCreate) SetNillableID(v *uuid.UUID) *LinkItemCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPage sets the "page" edge to the Page entity.
func (_c *LinkItemCreate) SetPage(v *Page) *LinkItemCreate {
	return _c.SetPageID(v.ID)
}

// Mutation returns the LinkItemMutation object of the builder.
func (_c *LinkItemCreate) Mutation() *LinkItemMutation {
	return _c.mutation
}

// Save creates the LinkItem in the database.
func (_c *LinkItemCreate) Save(ctx context.Context) (*LinkItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LinkItemCreate) SaveX(ctx context.Context) *LinkItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LinkItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := linkitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := linkitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := linkitem.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := linkitem.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LinkItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LinkItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LinkItem.updated_at"`)}
	}
	if _, ok := _c.mutation.PageID(); !ok {
		return &ValidationError{Name: "page_id", err: errors.New(`ent: missing required field "LinkItem.page_id"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "LinkItem.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := linkitem.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "LinkItem.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "LinkItem.priority"`)}
	}
	if len(_c.mutation.PageIDs()) == 0 {
		return &ValidationError{Name: "page", err: errors.New(`ent: missing required edge "LinkItem.page"`)}
	}
	return nil
}

func (_c *LinkItemCreate) sqlSave(ctx context.Context) (*LinkItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LinkItemCreate) createSpec() (*LinkItem, *sqlgraph.CreateSpec) {
	var (
		_node = &LinkItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(linkitem.Table, sqlgraph.NewFieldSpec(linkitem.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.LinkItem
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(linkitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(linkitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(linkitem.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Memo(); ok {
		_spec.SetField(linkitem.FieldMemo, field.TypeString, value)
		_node.Memo = &value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(linkitem.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if nodes := _c.mutation.PageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   linkitem.PageTable,
			Columns: []string{linkitem.PageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(page.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.LinkItem
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LinkItemCreateBulk is the builder for creating many LinkItem entities in bulk.
type LinkItemCreateBulk struct {
	config
	err      error
	builders []*LinkItemCreate
}

// Save creates the LinkItem entities in the database.
func (_c *LinkItemCreateBulk) Save(ctx context.Context) ([]*LinkItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LinkItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LinkItemCreateBulk) SaveX(ctx context.Context) []*LinkItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
