// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/internal"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/linkitem"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/predicate"
)

// LinkItemDelete is the builder for deleting a LinkItem entity.
type LinkItemDelete struct {
	config
	hooks    []Hook
	mutation *LinkItemMutation
}

// Where appends a list predicates to the LinkItemDelete builder.
func (_d *LinkItemDelete) Where(ps ...predicate.LinkItem) *LinkItemDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LinkItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LinkItemDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LinkItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(linkitem.Table, sqlgraph.NewFieldSpec(linkitem.FieldID, field.TypeUUID))
	_spec.Node.Schema = _d.schemaConfig.LinkItem
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LinkItemDeleteOne is the builder for deleting a single LinkItem entity.
type LinkItemDeleteOne struct {
	_d *LinkItemDelete
}

// Where appends a list predicates to the LinkItemDelete builder.
func (_d *LinkItemDeleteOne) Where(ps ...predicate.LinkItem) *LinkItemDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LinkItemDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{linkitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LinkItemDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
