// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/linkitem"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/page"
)

// LinkItem is the model entity for the LinkItem schema.
type LinkItem struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PageID holds the value of the "page_id" field.
	PageID uuid.UUID `json:"page_id,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Memo holds the value of the "memo" field.
	Memo *string `json:"memo,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LinkItemQuery when eager-loading is set.
	Edges        LinkItemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LinkItemEdges holds the relations/edges for other nodes in the graph.
type LinkItemEdges struct {
	// Page holds the value of the page edge.
	Page *Page `json:"page,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PageOrErr returns the Page value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LinkItemEdges) PageOrErr() (*Page, error) {
	if e.Page != nil {
		return e.Page, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: page.Label}
	}
	return nil, &NotLoadedError{edge: "page"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LinkItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case linkitem.FieldPriority:
			values[i] = new(sql.NullInt64)
		case linkitem.FieldURL, linkitem.FieldMemo:
			values[i] = new(sql.NullString)
		case linkitem.FieldCreatedAt, linkitem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case linkitem.FieldID, linkitem.FieldPageID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LinkItem fields.
func (_m *LinkItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case linkitem.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case linkitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case linkitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case linkitem.FieldPageID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field page_id", values[i])
			} else if value != nil {
				_m.PageID = *value
			}
		case linkitem.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case linkitem.FieldMemo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field memo", values[i])
			} else if value.Valid {
				_m.Memo = new(string)
				*_m.Memo = value.String
			}
		case linkitem.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LinkItem.
// This includes values selected through modifiers, order, etc.
func (_m *LinkItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPage queries the "page" edge of the LinkItem entity.
func (_m *LinkItem) QueryPage() *PageQuery {
	return NewLinkItemClient(_m.config).QueryPage(_m)
}

// Update returns a builder for updating this LinkItem.
// Note that you need to call LinkItem.Unwrap() before calling this method if this LinkItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LinkItem) Update() *LinkItemUpdateOne {
	return NewLinkItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LinkItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LinkItem) Unwrap() *LinkItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LinkItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LinkItem) String() string {
	var builder strings.Builder
	builder.WriteString("LinkItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("page_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PageID))
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	if v := _m.Memo; v != nil {
		builder.WriteString("memo=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteByte(')')
	return builder.String()
}

// LinkItems is a parsable slice of LinkItem.
type LinkItems []*LinkItem
