// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/internal"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/linkitem"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/page"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/predicate"
)

// LinkItemQuery is the builder for querying LinkItem entities.
type LinkItemQuery struct {
	config
	ctx        *QueryContext
	order      []linkitem.OrderOption
	inters     []Interceptor
	predicates []predicate.LinkItem
	withPage   *PageQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LinkItemQuery builder.
func (_q *LinkItemQuery) Where(ps ...predicate.LinkItem) *LinkItemQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *LinkItemQuery) Limit(limit int) *LinkItemQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *LinkItemQuery) Offset(offset int) *LinkItemQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *LinkItemQuery) Unique(unique bool) *LinkItemQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *LinkItemQuery) Order(o ...linkitem.OrderOption) *LinkItemQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPage chains the current query on the "page" edge.
func (_q *LinkItemQuery) QueryPage() *PageQuery {
	query := (&PageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(linkitem.Table, linkitem.FieldID, selector),
			sqlgraph.To(page.Table, page.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, linkitem.PageTable, linkitem.PageColumn),
		)
		schemaConfig := _q.schemaConfig
		step.To.Schema = schemaConfig.Page
		step.Edge.Schema = schemaConfig.LinkItem
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LinkItem entity from the query.
// Returns a *NotFoundError when no LinkItem was found.
func (_q *LinkItemQuery) First(ctx context.Context) (*LinkItem, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{linkitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *LinkItemQuery) FirstX(ctx context.Context) *LinkItem {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LinkItem ID from the query.
// Returns a *NotFoundError when no LinkItem ID was found.
func (_q *LinkItemQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{linkitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *LinkItemQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LinkItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LinkItem entity is found.
// Returns a *NotFoundError when no LinkItem entities are found.
func (_q *LinkItemQuery) Only(ctx context.Context) (*LinkItem, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{linkitem.Label}
	default:
		return nil, &NotSingularError{linkitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *LinkItemQuery) OnlyX(ctx context.Context) *LinkItem {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LinkItem ID in the query.
// Returns a *NotSingularError when more than one LinkItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *LinkItemQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{linkitem.Label}
	default:
		err = &NotSingularError{linkitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *LinkItemQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LinkItems.
func (_q *LinkItemQuery) All(ctx context.Context) ([]*LinkItem, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LinkItem, *LinkItemQuery]()
	return withInterceptors[[]*LinkItem](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *LinkItemQuery) AllX(ctx context.Context) []*LinkItem {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LinkItem IDs.
func (_q *LinkItemQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(linkitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *LinkItemQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *LinkItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*LinkItemQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *LinkItemQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *LinkItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *LinkItemQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LinkItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *LinkItemQuery) Clone() *LinkItemQuery {
	if _q == nil {
		return nil
	}
	return &LinkItemQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]linkitem.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.LinkItem{}, _q.predicates...),
		withPage:   _q.withPage.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPage tells the query-builder to eager-load the nodes that are connected to
// the "page" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LinkItemQuery) WithPage(opts ...func(*PageQuery)) *LinkItemQuery {
	query := (&PageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPage = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LinkItem.Query().
//		GroupBy(linkitem.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *LinkItemQuery) GroupBy(field string, fields ...string) *LinkItemGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LinkItemGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = linkitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.LinkItem.Query().
//		Select(linkitem.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *LinkItemQuery) Select(fields ...string) *LinkItemSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &LinkItemSelect{LinkItemQuery: _q}
	sbuild.label = linkitem.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LinkItemSelect configured with the given aggregations.
func (_q *LinkItemQuery) Aggregate(fns ...AggregateFunc) *LinkItemSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *LinkItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !linkitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *LinkItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LinkItem, error) {
	var (
		nodes       = []*LinkItem{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withPage != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LinkItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LinkItem{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.LinkItem
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPage; query != nil {
		if err := _q.loadPage(ctx, query, nodes, nil,
			func(n *LinkItem, e *Page) { n.Edges.Page = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *LinkItemQuery) loadPage(ctx context.Context, query *PageQuery, nodes []*LinkItem, init func(*LinkItem), assign func(*LinkItem, *Page)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*LinkItem)
	for i := range nodes {
		fk := nodes[i].PageID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(page.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "page_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *LinkItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.LinkItem
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *LinkItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(linkitem.Table, linkitem.Columns, sqlgraph.NewFieldSpec(linkitem.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linkitem.FieldID)
		for i := range fields {
			if fields[i] != linkitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withPage != nil {
			_spec.Node.AddColumnOnce(linkitem.FieldPageID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *LinkItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(linkitem.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = linkitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.LinkItem)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LinkItemGroupBy is the group-by builder for LinkItem entities.
type LinkItemGroupBy struct {
	selector
	build *LinkItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *LinkItemGroupBy) Aggregate(fns ...AggregateFunc) *LinkItemGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *LinkItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LinkItemQuery, *LinkItemGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *LinkItemGroupBy) sqlScan(ctx context.Context, root *LinkItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LinkItemSelect is the builder for selecting fields of LinkItem entities.
type LinkItemSelect struct {
	*LinkItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *LinkItemSelect) Aggregate(fns ...AggregateFunc) *LinkItemSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *LinkItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LinkItemQuery, *LinkItemSelect](ctx, _s.LinkItemQuery, _s, _s.inters, v)
}

func (_s *LinkItemSelect) sqlScan(ctx context.Context, root *LinkItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
