// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/linkitem"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/page"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/predicate"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/user"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeLinkItem = "LinkItem"
	TypePage     = "Page"
	TypeUser     = "User"
)

// LinkItemMutation represents an operation that mutates the LinkItem nodes in the graph.
type LinkItemMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	created_at    *time.Time
	updated_at    *time.Time
	url           *string
	memo          *string
	priority      *int
	addpriority   *int
	clearedFields map[string]struct{}
	page          *uuid.UUID
	clearedpage   bool
	done          bool
	oldValue      func(context.Context) (*LinkItem, error)
	predicates    []predicate.LinkItem
}

var _ ent.Mutation = (*LinkItemMutation)(nil)

// linkitemOption allows management of the mutation configuration using functional options.
type linkitemOption func(*LinkItemMutation)

// newLinkItemMutation creates new mutation for the LinkItem entity.
func newLinkItemMutation(c config, op Op, opts ...linkitemOption) *LinkItemMutation {
	m := &LinkItemMutation{
		config:        c,
		op:            op,
		typ:           TypeLinkItem,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withLinkItemID sets the ID field of the mutation.
func withLinkItemID(id uuid.UUID) linkitemOption {
	return func(m *LinkItemMutation) {
		var (
			err   error
			once  sync.Once
			value *LinkItem
		)
		m.oldValue = func(ctx context.Context) (*LinkItem, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().LinkItem.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withLinkItem sets the old LinkItem of the mutation.
func withLinkItem(node *LinkItem) linkitemOption {
	return func(m *LinkItemMutation) {
		m.oldValue = func(context.Context) (*LinkItem, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m LinkItemMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m LinkItemMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of LinkItem entities.
func (m *LinkItemMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *LinkItemMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *LinkItemMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().LinkItem.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *LinkItemMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *LinkItemMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the LinkItem entity.
// If the LinkItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LinkItemMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *LinkItemMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *LinkItemMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *LinkItemMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the LinkItem entity.
// If the LinkItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LinkItemMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *LinkItemMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetPageID sets the "page_id" field.
func (m *LinkItemMutation) SetPageID(u uuid.UUID) {
	m.page = &u
}

// PageID returns the value of the "page_id" field in the mutation.
func (m *LinkItemMutation) PageID() (r uuid.UUID, exists bool) {
	v := m.page
	if v == nil {
		return
	}
	return *v, true
}

// OldPageID returns the old "page_id" field's value of the LinkItem entity.
// If the LinkItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LinkItemMutation) OldPageID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPageID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPageID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPageID: %w", err)
	}
	return oldValue.PageID, nil
}

// ResetPageID resets all changes to the "page_id" field.
func (m *LinkItemMutation) ResetPageID() {
	m.page = nil
}

// SetURL sets the "url" field.
func (m *LinkItemMutation) SetURL(s string) {
	m.url = &s
}

// URL returns the value of the "url" field in the mutation.
func (m *LinkItemMutation) URL() (r string, exists bool) {
	v := m.url
	if v == nil {
		return
	}
	return *v, true
}

// OldURL returns the old "url" field's value of the LinkItem entity.
// If the LinkItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LinkItemMutation) OldURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURL: %w", err)
	}
	return oldValue.URL, nil
}

// ResetURL resets all changes to the "url" field.
func (m *LinkItemMutation) ResetURL() {
	m.url = nil
}

// SetMemo sets the "memo" field.
func (m *LinkItemMutation) SetMemo(s string) {
	m.memo = &s
}

// Memo returns the value of the "memo" field in the mutation.
func (m *LinkItemMutation) Memo() (r string, exists bool) {
	v := m.memo
	if v == nil {
		return
	}
	return *v, true
}

// OldMemo returns the old "memo" field's value of the LinkItem entity.
// If the LinkItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LinkItemMutation) OldMemo(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMemo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMemo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMemo: %w", err)
	}
	return oldValue.Memo, nil
}

// ClearMemo clears the value of the "memo" field.
func (m *LinkItemMutation) ClearMemo() {
	m.memo = nil
	m.clearedFields[linkitem.FieldMemo] = struct{}{}
}

// MemoCleared returns if the "memo" field was cleared in this mutation.
func (m *LinkItemMutation) MemoCleared() bool {
	_, ok := m.clearedFields[linkitem.FieldMemo]
	return ok
}

// ResetMemo resets all changes to the "memo" field.
func (m *LinkItemMutation) ResetMemo() {
	m.memo = nil
	delete(m.clearedFields, linkitem.FieldMemo)
}

// SetPriority sets the "priority" field.
func (m *LinkItemMutation) SetPriority(i int) {
	m.priority = &i
	m.addpriority = nil
}

// Priority returns the value of the "priority" field in the mutation.
func (m *LinkItemMutation) Priority() (r int, exists bool) {
	v := m.priority
	if v == nil {
		return
	}
	return *v, true
}

// OldPriority returns the old "priority" field's value of the LinkItem entity.
// If the LinkItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LinkItemMutation) OldPriority(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPriority is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPriority requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPriority: %w", err)
	}
	return oldValue.Priority, nil
}

// AddPriority adds i to the "priority" field.
func (m *LinkItemMutation) AddPriority(i int) {
	if m.addpriority != nil {
		*m.addpriority += i
	} else {
		m.addpriority = &i
	}
}

// AddedPriority returns the value that was added to the "priority" field in this mutation.
func (m *LinkItemMutation) AddedPriority() (r int, exists bool) {
	v := m.addpriority
	if v == nil {
		return
	}
	return *v, true
}

// ResetPriority resets all changes to the "priority" field.
func (m *LinkItemMutation) ResetPriority() {
	m.priority = nil
	m.addpriority = nil
}

// ClearPage clears the "page" edge to the Page entity.
func (m *LinkItemMutation) ClearPage() {
	m.clearedpage = true
	m.clearedFields[linkitem.FieldPageID] = struct{}{}
}

// PageCleared reports if the "page" edge to the Page entity was cleared.
func (m *LinkItemMutation) PageCleared() bool {
	return m.clearedpage
}

// PageIDs returns the "page" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// PageID instead. It exists only for internal usage by the builders.
func (m *LinkItemMutation) PageIDs() (ids []uuid.UUID) {
	if id := m.page; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetPage resets all changes to the "page" edge.
func (m *LinkItemMutation) ResetPage() {
	m.page = nil
	m.clearedpage = false
}

// Where appends a list predicates to the LinkItemMutation builder.
func (m *LinkItemMutation) Where(ps ...predicate.LinkItem) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the LinkItemMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *LinkItemMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.LinkItem, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *LinkItemMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *LinkItemMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (LinkItem).
func (m *LinkItemMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *LinkItemMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.created_at != nil {
		fields = append(fields, linkitem.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, linkitem.FieldUpdatedAt)
	}
	if m.page != nil {
		fields = append(fields, linkitem.FieldPageID)
	}
	if m.url != nil {
		fields = append(fields, linkitem.FieldURL)
	}
	if m.memo != nil {
		fields = append(fields, linkitem.FieldMemo)
	}
	if m.priority != nil {
		fields = append(fields, linkitem.FieldPriority)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *LinkItemMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case linkitem.FieldCreatedAt:
		return m.CreatedAt()
	case linkitem.FieldUpdatedAt:
		return m.UpdatedAt()
	case linkitem.FieldPageID:
		return m.PageID()
	case linkitem.FieldURL:
		return m.URL()
	case linkitem.FieldMemo:
		return m.Memo()
	case linkitem.FieldPriority:
		return m.Priority()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *LinkItemMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case linkitem.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case linkitem.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case linkitem.FieldPageID:
		return m.OldPageID(ctx)
	case linkitem.FieldURL:
		return m.OldURL(ctx)
	case linkitem.FieldMemo:
		return m.OldMemo(ctx)
	case linkitem.FieldPriority:
		return m.OldPriority(ctx)
	}
	return nil, fmt.Errorf("unknown LinkItem field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LinkItemMutation) SetField(name string, value ent.Value) error {
	switch name {
	case linkitem.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case linkitem.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case linkitem.FieldPageID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPageID(v)
		return nil
	case linkitem.FieldURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURL(v)
		return nil
	case linkitem.FieldMemo:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMemo(v)
		return nil
	case linkitem.FieldPriority:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPriority(v)
		return nil
	}
	return fmt.Errorf("unknown LinkItem field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *LinkItemMutation) AddedFields() []string {
	var fields []string
	if m.addpriority != nil {
		fields = append(fields, linkitem.FieldPriority)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *LinkItemMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case linkitem.FieldPriority:
		return m.AddedPriority()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LinkItemMutation) AddField(name string, value ent.Value) error {
	switch name {
	case linkitem.FieldPriority:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPriority(v)
		return nil
	}
	return fmt.Errorf("unknown LinkItem numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *LinkItemMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(linkitem.FieldMemo) {
		fields = append(fields, linkitem.FieldMemo)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *LinkItemMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *LinkItemMutation) ClearField(name string) error {
	switch name {
	case linkitem.FieldMemo:
		m.ClearMemo()
		return nil
	}
	return fmt.Errorf("unknown LinkItem nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *LinkItemMutation) ResetField(name string) error {
	switch name {
	case linkitem.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case linkitem.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case linkitem.FieldPageID:
		m.ResetPageID()
		return nil
	case linkitem.FieldURL:
		m.ResetURL()
		return nil
	case linkitem.FieldMemo:
		m.ResetMemo()
		return nil
	case linkitem.FieldPriority:
		m.ResetPriority()
		return nil
	}
	return fmt.Errorf("unknown LinkItem field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *LinkItemMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.page != nil {
		edges = append(edges, linkitem.EdgePage)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *LinkItemMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case linkitem.EdgePage:
		if id := m.page; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *LinkItemMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *LinkItemMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *LinkItemMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedpage {
		edges = append(edges, linkitem.EdgePage)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *LinkItemMutation) EdgeCleared(name string) bool {
	switch name {
	case linkitem.EdgePage:
		return m.clearedpage
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *LinkItemMutation) ClearEdge(name string) error {
	switch name {
	case linkitem.EdgePage:
		m.ClearPage()
		return nil
	}
	return fmt.Errorf("unknown LinkItem unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *LinkItemMutation) ResetEdge(name string) error {
	switch name {
	case linkitem.EdgePage:
		m.ResetPage()
		return nil
	}
	return fmt.Errorf("unknown LinkItem edge %s", name)
}

// PageMutation represents an operation that mutates the Page nodes in the graph.
type PageMutation struct {
	config
	op                   Op
	typ                  string
	id                   *uuid.UUID
	created_at           *time.Time
	updated_at           *time.Time
	title                *string
	invite_code          *string
	clearedFields        map[string]struct{}
	creator              *uuid.UUID
	clearedcreator       bool
	link_items           map[uuid.UUID]struct{}
	removedlink_items    map[uuid.UUID]struct{}
	clearedlink_items    bool
	invited_users        map[uuid.UUID]struct{}
	removedinvited_users map[uuid.UUID]struct{}
	clearedinvited_users bool
	done                 bool
	oldValue             func(context.Context) (*Page, error)
	predicates           []predicate.Page
}

var _ ent.Mutation = (*PageMutation)(nil)

// pageOption allows management of the mutation configuration using functional options.
type pageOption func(*PageMutation)

// newPageMutation creates new mutation for the Page entity.
func newPageMutation(c config, op Op, opts ...pageOption) *PageMutation {
	m := &PageMutation{
		config:        c,
		op:            op,
		typ:           TypePage,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPageID sets the ID field of the mutation.
func withPageID(id uuid.UUID) pageOption {
	return func(m *PageMutation) {
		var (
			err   error
			once  sync.Once
			value *Page
		)
		m.oldValue = func(ctx context.Context) (*Page, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Page.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPage sets the old Page of the mutation.
func withPage(node *Page) pageOption {
	return func(m *PageMutation) {
		m.oldValue = func(context.Context) (*Page, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PageMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PageMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Page entities.
func (m *PageMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PageMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PageMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Page.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *PageMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PageMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Page entity.
// If the Page object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PageMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *PageMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *PageMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Page entity.
// If the Page object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *PageMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetTitle sets the "title" field.
func (m *PageMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *PageMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Page entity.
// If the Page object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *PageMutation) ResetTitle() {
	m.title = nil
}

// SetCreatorID sets the "creator_id" field.
func (m *PageMutation) SetCreatorID(u uuid.UUID) {
	m.creator = &u
}

// CreatorID returns the value of the "creator_id" field in the mutation.
func (m *PageMutation) CreatorID() (r uuid.UUID, exists bool) {
	v := m.creator
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatorID returns the old "creator_id" field's value of the Page entity.
// If the Page object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageMutation) OldCreatorID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatorID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatorID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatorID: %w", err)
	}
	return oldValue.CreatorID, nil
}

// ResetCreatorID resets all changes to the "creator_id" field.
func (m *PageMutation) ResetCreatorID() {
	m.creator = nil
}

// SetInviteCode sets the "invite_code" field.
func (m *PageMutation) SetInviteCode(s string) {
	m.invite_code = &s
}

// InviteCode returns the value of the "invite_code" field in the mutation.
func (m *PageMutation) InviteCode() (r string, exists bool) {
	v := m.invite_code
	if v == nil {
		return
	}
	return *v, true
}

// OldInviteCode returns the old "invite_code" field's value of the Page entity.
// If the Page object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageMutation) OldInviteCode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInviteCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInviteCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInviteCode: %w", err)
	}
	return oldValue.InviteCode, nil
}

// ResetInviteCode resets all changes to the "invite_code" field.
func (m *PageMutation) ResetInviteCode() {
	m.invite_code = nil
}

// ClearCreator clears the "creator" edge to the User entity.
func (m *PageMutation) ClearCreator() {
	m.clearedcreator = true
	m.clearedFields[page.FieldCreatorID] = struct{}{}
}

// CreatorCleared reports if the "creator" edge to the User entity was cleared.
func (m *PageMutation) CreatorCleared() bool {
	return m.clearedcreator
}

// CreatorIDs returns the "creator" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// CreatorID instead. It exists only for internal usage by the builders.
func (m *PageMutation) CreatorIDs() (ids []uuid.UUID) {
	if id := m.creator; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetCreator resets all changes to the "creator" edge.
func (m *PageMutation) ResetCreator() {
	m.creator = nil
	m.clearedcreator = false
}

// AddLinkItemIDs adds the "link_items" edge to the LinkItem entity by ids.
func (m *PageMutation) AddLinkItemIDs(ids ...uuid.UUID) {
	if m.link_items == nil {
		m.link_items = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.link_items[ids[i]] = struct{}{}
	}
}

// ClearLinkItems clears the "link_items" edge to the LinkItem entity.
func (m *PageMutation) ClearLinkItems() {
	m.clearedlink_items = true
}

// LinkItemsCleared reports if the "link_items" edge to the LinkItem entity was cleared.
func (m *PageMutation) LinkItemsCleared() bool {
	return m.clearedlink_items
}

// RemoveLinkItemIDs removes the "link_items" edge to the LinkItem entity by IDs.
func (m *PageMutation) RemoveLinkItemIDs(ids ...uuid.UUID) {
	if m.removedlink_items == nil {
		m.removedlink_items = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.link_items, ids[i])
		m.removedlink_items[ids[i]] = struct{}{}
	}
}

// RemovedLinkItems returns the removed IDs of the "link_items" edge to the LinkItem entity.
func (m *PageMutation) RemovedLinkItemsIDs() (ids []uuid.UUID) {
	for id := range m.removedlink_items {
		ids = append(ids, id)
	}
	return
}

// LinkItemsIDs returns the "link_items" edge IDs in the mutation.
func (m *PageMutation) LinkItemsIDs() (ids []uuid.UUID) {
	for id := range m.link_items {
		ids = append(ids, id)
	}
	return
}

// ResetLinkItems resets all changes to the "link_items" edge.
func (m *PageMutation) ResetLinkItems() {
	m.link_items = nil
	m.clearedlink_items = false
	m.removedlink_items = nil
}

// AddInvitedUserIDs adds the "invited_users" edge to the User entity by ids.
func (m *PageMutation) AddInvitedUserIDs(ids ...uuid.UUID) {
	if m.invited_users == nil {
		m.invited_users = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.invited_users[ids[i]] = struct{}{}
	}
}

// ClearInvitedUsers clears the "invited_users" edge to the User entity.
func (m *PageMutation) ClearInvitedUsers() {
	m.clearedinvited_users = true
}

// InvitedUsersCleared reports if the "invited_users" edge to the User entity was cleared.
func (m *PageMutation) InvitedUsersCleared() bool {
	return m.clearedinvited_users
}

// RemoveInvitedUserIDs removes the "invited_users" edge to the User entity by IDs.
func (m *PageMutation) RemoveInvitedUserIDs(ids ...uuid.UUID) {
	if m.removedinvited_users == nil {
		m.removedinvited_users = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.invited_users, ids[i])
		m.removedinvited_users[ids[i]] = struct{}{}
	}
}

// RemovedInvitedUsers returns the removed IDs of the "invited_users" edge to the User entity.
func (m *PageMutation) RemovedInvitedUsersIDs() (ids []uuid.UUID) {
	for id := range m.removedinvited_users {
		ids = append(ids, id)
	}
	return
}

// InvitedUsersIDs returns the "invited_users" edge IDs in the mutation.
func (m *PageMutation) InvitedUsersIDs() (ids []uuid.UUID) {
	for id := range m.invited_users {
		ids = append(ids, id)
	}
	return
}

// ResetInvitedUsers resets all changes to the "invited_users" edge.
func (m *PageMutation) ResetInvitedUsers() {
	m.invited_users = nil
	m.clearedinvited_users = false
	m.removedinvited_users = nil
}

// Where appends a list predicates to the PageMutation builder.
func (m *PageMutation) Where(ps ...predicate.Page) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PageMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PageMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Page, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PageMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PageMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Page).
func (m *PageMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PageMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.created_at != nil {
		fields = append(fields, page.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, page.FieldUpdatedAt)
	}
	if m.title != nil {
		fields = append(fields, page.FieldTitle)
	}
	if m.creator != nil {
		fields = append(fields, page.FieldCreatorID)
	}
	if m.invite_code != nil {
		fields = append(fields, page.FieldInviteCode)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PageMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case page.FieldCreatedAt:
		return m.CreatedAt()
	case page.FieldUpdatedAt:
		return m.UpdatedAt()
	case page.FieldTitle:
		return m.Title()
	case page.FieldCreatorID:
		return m.CreatorID()
	case page.FieldInviteCode:
		return m.InviteCode()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PageMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case page.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case page.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case page.FieldTitle:
		return m.OldTitle(ctx)
	case page.FieldCreatorID:
		return m.OldCreatorID(ctx)
	case page.FieldInviteCode:
		return m.OldInviteCode(ctx)
	}
	return nil, fmt.Errorf("unknown Page field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PageMutation) SetField(name string, value ent.Value) error {
	switch name {
	case page.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case page.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case page.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case page.FieldCreatorID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatorID(v)
		return nil
	case page.FieldInviteCode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInviteCode(v)
		return nil
	}
	return fmt.Errorf("unknown Page field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PageMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PageMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PageMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Page numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PageMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PageMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PageMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Page nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PageMutation) ResetField(name string) error {
	switch name {
	case page.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case page.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case page.FieldTitle:
		m.ResetTitle()
		return nil
	case page.FieldCreatorID:
		m.ResetCreatorID()
		return nil
	case page.FieldInviteCode:
		m.ResetInviteCode()
		return nil
	}
	return fmt.Errorf("unknown Page field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PageMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.creator != nil {
		edges = append(edges, page.EdgeCreator)
	}
	if m.link_items != nil {
		edges = append(edges, page.EdgeLinkItems)
	}
	if m.invited_users != nil {
		edges = append(edges, page.EdgeInvitedUsers)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PageMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case page.EdgeCreator:
		if id := m.creator; id != nil {
			return []ent.Value{*id}
		}
	case page.EdgeLinkItems:
		ids := make([]ent.Value, 0, len(m.link_items))
		for id := range m.link_items {
			ids = append(ids, id)
		}
		return ids
	case page.EdgeInvitedUsers:
		ids := make([]ent.Value, 0, len(m.invited_users))
		for id := range m.invited_users {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PageMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedlink_items != nil {
		edges = append(edges, page.EdgeLinkItems)
	}
	if m.removedinvited_users != nil {
		edges = append(edges, page.EdgeInvitedUsers)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PageMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case page.EdgeLinkItems:
		ids := make([]ent.Value, 0, len(m.removedlink_items))
		for id := range m.removedlink_items {
			ids = append(ids, id)
		}
		return ids
	case page.EdgeInvitedUsers:
		ids := make([]ent.Value, 0, len(m.removedinvited_users))
		for id := range m.removedinvited_users {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PageMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedcreator {
		edges = append(edges, page.EdgeCreator)
	}
	if m.clearedlink_items {
		edges = append(edges, page.EdgeLinkItems)
	}
	if m.clearedinvited_users {
		edges = append(edges, page.EdgeInvitedUsers)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PageMutation) EdgeCleared(name string) bool {
	switch name {
	case page.EdgeCreator:
		return m.clearedcreator
	case page.EdgeLinkItems:
		return m.clearedlink_items
	case page.EdgeInvitedUsers:
		return m.clearedinvited_users
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PageMutation) ClearEdge(name string) error {
	switch name {
	case page.EdgeCreator:
		m.ClearCreator()
		return nil
	}
	return fmt.Errorf("unknown Page unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PageMutation) ResetEdge(name string) error {
	switch name {
	case page.EdgeCreator:
		m.ResetCreator()
		return nil
	case page.EdgeLinkItems:
		m.ResetLinkItems()
		return nil
	case page.EdgeInvitedUsers:
		m.ResetInvitedUsers()
		return nil
	}
	return fmt.Errorf("unknown Page edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                   Op
	typ                  string
	id                   *uuid.UUID
	created_at           *time.Time
	updated_at           *time.Time
	uid                  *string
	provider             *user.Provider
	email                *string
	clearedFields        map[string]struct{}
	created_pages        map[uuid.UUID]struct{}
	removedcreated_pages map[uuid.UUID]struct{}
	clearedcreated_pages bool
	invited_pages        map[uuid.UUID]struct{}
	removedinvited_pages map[uuid.UUID]struct{}
	clearedinvited_pages bool
	done                 bool
	oldValue             func(context.Context) (*User, error)
	predicates           []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id uuid.UUID) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *UserMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetUID sets the "uid" field.
func (m *UserMutation) SetUID(s string) {
	m.uid = &s
}

// UID returns the value of the "uid" field in the mutation.
func (m *UserMutation) UID() (r string, exists bool) {
	v := m.uid
	if v == nil {
		return
	}
	return *v, true
}

// OldUID returns the old "uid" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUID: %w", err)
	}
	return oldValue.UID, nil
}

// ResetUID resets all changes to the "uid" field.
func (m *UserMutation) ResetUID() {
	m.uid = nil
}

// SetProvider sets the "provider" field.
func (m *UserMutation) SetProvider(u user.Provider) {
	m.provider = &u
}

// Provider returns the value of the "provider" field in the mutation.
func (m *UserMutation) Provider() (r user.Provider, exists bool) {
	v := m.provider
	if v == nil {
		return
	}
	return *v, true
}

// OldProvider returns the old "provider" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldProvider(ctx context.Context) (v user.Provider, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProvider is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProvider requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProvider: %w", err)
	}
	return oldValue.Provider, nil
}

// ResetProvider resets all changes to the "provider" field.
func (m *UserMutation) ResetProvider() {
	m.provider = nil
}

// SetEmail sets the "email" field.
func (m *UserMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *UserMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldEmail(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ClearEmail clears the value of the "email" field.
func (m *UserMutation) ClearEmail() {
	m.email = nil
	m.clearedFields[user.FieldEmail] = struct{}{}
}

// EmailCleared returns if the "email" field was cleared in this mutation.
func (m *UserMutation) EmailCleared() bool {
	_, ok := m.clearedFields[user.FieldEmail]
	return ok
}

// ResetEmail resets all changes to the "email" field.
func (m *UserMutation) ResetEmail() {
	m.email = nil
	delete(m.clearedFields, user.FieldEmail)
}

// AddCreatedPageIDs adds the "created_pages" edge to the Page entity by ids.
func (m *UserMutation) AddCreatedPageIDs(ids ...uuid.UUID) {
	if m.created_pages == nil {
		m.created_pages = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.created_pages[ids[i]] = struct{}{}
	}
}

// ClearCreatedPages clears the "created_pages" edge to the Page entity.
func (m *UserMutation) ClearCreatedPages() {
	m.clearedcreated_pages = true
}

// CreatedPagesCleared reports if the "created_pages" edge to the Page entity was cleared.
func (m *UserMutation) CreatedPagesCleared() bool {
	return m.clearedcreated_pages
}

// RemoveCreatedPageIDs removes the "created_pages" edge to the Page entity by IDs.
func (m *UserMutation) RemoveCreatedPageIDs(ids ...uuid.UUID) {
	if m.removedcreated_pages == nil {
		m.removedcreated_pages = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.created_pages, ids[i])
		m.removedcreated_pages[ids[i]] = struct{}{}
	}
}

// RemovedCreatedPages returns the removed IDs of the "created_pages" edge to the Page entity.
func (m *UserMutation) RemovedCreatedPagesIDs() (ids []uuid.UUID) {
	for id := range m.removedcreated_pages {
		ids = append(ids, id)
	}
	return
}

// CreatedPagesIDs returns the "created_pages" edge IDs in the mutation.
func (m *UserMutation) CreatedPagesIDs() (ids []uuid.UUID) {
	for id := range m.created_pages {
		ids = append(ids, id)
	}
	return
}

// ResetCreatedPages resets all changes to the "created_pages" edge.
func (m *UserMutation) ResetCreatedPages() {
	m.created_pages = nil
	m.clearedcreated_pages = false
	m.removedcreated_pages = nil
}

// AddInvitedPageIDs adds the "invited_pages" edge to the Page entity by ids.
func (m *UserMutation) AddInvitedPageIDs(ids ...uuid.UUID) {
	if m.invited_pages == nil {
		m.invited_pages = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.invited_pages[ids[i]] = struct{}{}
	}
}

// ClearInvitedPages clears the "invited_pages" edge to the Page entity.
func (m *UserMutation) ClearInvitedPages() {
	m.clearedinvited_pages = true
}

// InvitedPagesCleared reports if the "invited_pages" edge to the Page entity was cleared.
func (m *UserMutation) InvitedPagesCleared() bool {
	return m.clearedinvited_pages
}

// RemoveInvitedPageIDs removes the "invited_pages" edge to the Page entity by IDs.
func (m *UserMutation) RemoveInvitedPageIDs(ids ...uuid.UUID) {
	if m.removedinvited_pages == nil {
		m.removedinvited_pages = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.invited_pages, ids[i])
		m.removedinvited_pages[ids[i]] = struct{}{}
	}
}

// RemovedInvitedPages returns the removed IDs of the "invited_pages" edge to the Page entity.
func (m *UserMutation) RemovedInvitedPagesIDs() (ids []uuid.UUID) {
	for id := range m.removedinvited_pages {
		ids = append(ids, id)
	}
	return
}

// InvitedPagesIDs returns the "invited_pages" edge IDs in the mutation.
func (m *UserMutation) InvitedPagesIDs() (ids []uuid.UUID) {
	for id := range m.invited_pages {
		ids = append(ids, id)
	}
	return
}

// ResetInvitedPages resets all changes to the "invited_pages" edge.
func (m *UserMutation) ResetInvitedPages() {
	m.invited_pages = nil
	m.clearedinvited_pages = false
	m.removedinvited_pages = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.created_at != nil {
		fields = append(fields, user.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, user.FieldUpdatedAt)
	}
	if m.uid != nil {
		fields = append(fields, user.FieldUID)
	}
	if m.provider != nil {
		fields = append(fields, user.FieldProvider)
	}
	if m.email != nil {
		fields = append(fields, user.FieldEmail)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldCreatedAt:
		return m.CreatedAt()
	case user.FieldUpdatedAt:
		return m.UpdatedAt()
	case user.FieldUID:
		return m.UID()
	case user.FieldProvider:
		return m.Provider()
	case user.FieldEmail:
		return m.Email()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case user.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case user.FieldUID:
		return m.OldUID(ctx)
	case user.FieldProvider:
		return m.OldProvider(ctx)
	case user.FieldEmail:
		return m.OldEmail(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case user.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case user.FieldUID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUID(v)
		return nil
	case user.FieldProvider:
		v, ok := value.(user.Provider)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProvider(v)
		return nil
	case user.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(user.FieldEmail) {
		fields = append(fields, user.FieldEmail)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	switch name {
	case user.FieldEmail:
		m.ClearEmail()
		return nil
	}
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case user.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case user.FieldUID:
		m.ResetUID()
		return nil
	case user.FieldProvider:
		m.ResetProvider()
		return nil
	case user.FieldEmail:
		m.ResetEmail()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.created_pages != nil {
		edges = append(edges, user.EdgeCreatedPages)
	}
	if m.invited_pages != nil {
		edges = append(edges, user.EdgeInvitedPages)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeCreatedPages:
		ids := make([]ent.Value, 0, len(m.created_pages))
		for id := range m.created_pages {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeInvitedPages:
		ids := make([]ent.Value, 0, len(m.invited_pages))
		for id := range m.invited_pages {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedcreated_pages != nil {
		edges = append(edges, user.EdgeCreatedPages)
	}
	if m.removedinvited_pages != nil {
		edges = append(edges, user.EdgeInvitedPages)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeCreatedPages:
		ids := make([]ent.Value, 0, len(m.removedcreated_pages))
		for id := range m.removedcreated_pages {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeInvitedPages:
		ids := make([]ent.Value, 0, len(m.removedinvited_pages))
		for id := range m.removedinvited_pages {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedcreated_pages {
		edges = append(edges, user.EdgeCreatedPages)
	}
	if m.clearedinvited_pages {
		edges = append(edges, user.EdgeInvitedPages)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeCreatedPages:
		return m.clearedcreated_pages
	case user.EdgeInvitedPages:
		return m.clearedinvited_pages
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeCreatedPages:
		m.ResetCreatedPages()
		return nil
	case user.EdgeInvitedPages:
		m.ResetInvitedPages()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
