// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/internal"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/linkitem"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/page"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/predicate"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/user"
)

// PageUpdate is the builder for updating Page entities.
type PageUpdate struct {
	config
	hooks    []Hook
	mutation *PageMutation
}

// Where appends a list predicates to the PageUpdate builder.
func (_u *PageUpdate) Where(ps ...predicate.Page) *PageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PageUpdate) SetUpdatedAt(v time.Time) *PageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *PageUpdate) SetTitle(v string) *PageUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PageUpdate) SetNillableTitle(v *string) *PageUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *PageUpdate) SetCreatorID(v uuid.UUID) *PageUpdate {
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *PageUpdate) SetNillableCreatorID(v *uuid.UUID) *PageUpdate {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// SetInviteCode sets the "invite_code" field.
func (_u *PageUpdate) SetInviteCode(v string) *PageUpdate {
	_u.mutation.SetInviteCode(v)
	return _u
}

// SetNillableInviteCode sets the "invite_code" field if the given value is not nil.
func (_u *PageUpdate) SetNillableInviteCode(v *string) *PageUpdate {
	if v != nil {
		_u.SetInviteCode(*v)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *PageUpdate) SetCreator(v *User) *PageUpdate {
	return _u.SetCreatorID(v.ID)
}

// AddLinkItemIDs adds the "link_items" edge to the LinkItem entity by IDs.
func (_u *PageUpdate) AddLinkItemIDs(ids ...uuid.UUID) *PageUpdate {
	_u.mutation.AddLinkItemIDs(ids...)
	return _u
}

// AddLinkItems adds the "link_items" edges to the LinkItem entity.
func (_u *PageUpdate) AddLinkItems(v ...*LinkItem) *PageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkItemIDs(ids...)
}

// AddInvitedUserIDs adds the "invited_users" edge to the User entity by IDs.
func (_u *PageUpdate) AddInvitedUserIDs(ids ...uuid.UUID) *PageUpdate {
	_u.mutation.AddInvitedUserIDs(ids...)
	return _u
}

// AddInvitedUsers adds the "invited_users" edges to the User entity.
func (_u *PageUpdate) AddInvitedUsers(v ...*User) *PageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvitedUserIDs(ids...)
}

// Mutation returns the PageMutation object of the builder.
func (_u *PageUpdate) Mutation() *PageMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *PageUpdate) ClearCreator() *PageUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearLinkItems clears all "link_items" edges to the LinkItem entity.
func (_u *PageUpdate) ClearLinkItems() *PageUpdate {
	_u.mutation.ClearLinkItems()
	return _u
}

// RemoveLinkItemIDs removes the "link_items" edge to LinkItem entities by IDs.
func (_u *PageUpdate) RemoveLinkItemIDs(ids ...uuid.UUID) *PageUpdate {
	_u.mutation.RemoveLinkItemIDs(ids...)
	return _u
}

// RemoveLinkItems removes "link_items" edges to LinkItem entities.
func (_u *PageUpdate) RemoveLinkItems(v ...*LinkItem) *PageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkItemIDs(ids...)
}

// ClearInvitedUsers clears all "invited_users" edges to the User entity.
func (_u *PageUpdate) ClearInvitedUsers() *PageUpdate {
	_u.mutation.ClearInvitedUsers()
	return _u
}

// RemoveInvitedUserIDs removes the "invited_users" edge to User entities by IDs.
func (_u *PageUpdate) RemoveInvitedUserIDs(ids ...uuid.UUID) *PageUpdate {
	_u.mutation.RemoveInvitedUserIDs(ids...)
	return _u
}

// RemoveInvitedUsers removes "invited_users" edges to User entities.
func (_u *PageUpdate) RemoveInvitedUsers(v ...*User) *PageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvitedUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := page.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PageUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := page.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Page.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InviteCode(); ok {
		if err := page.InviteCodeValidator(v); err != nil {
			return &ValidationError{Name: "invite_code", err: fmt.Errorf(`ent: validator failed for field "Page.invite_code": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Page.creator"`)
	}
	return nil
}

func (_u *PageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(page.Table, page.Columns, sqlgraph.NewFieldSpec(page.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(page.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(page.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.InviteCode(); ok {
		_spec.SetField(page.FieldInviteCode, field.TypeString, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.CreatorTable,
			Columns: []string{page.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Page
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.CreatorTable,
			Columns: []string{page.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Page
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinkItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   page.LinkItemsTable,
			Columns: []string{page.LinkItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkitem.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.LinkItem
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinkItemsIDs(); len(nodes) > 0 && !_u.mutation.LinkItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   page.LinkItemsTable,
			Columns: []string{page.LinkItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkitem.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.LinkItem
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinkItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   page.LinkItemsTable,
			Columns: []string{page.LinkItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkitem.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.LinkItem
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvitedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.InvitedUsersTable,
			Columns: page.InvitedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.PageInvitedUsers
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvitedUsersIDs(); len(nodes) > 0 && !_u.mutation.InvitedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.InvitedUsersTable,
			Columns: page.InvitedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.PageInvitedUsers
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvitedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.InvitedUsersTable,
			Columns: page.InvitedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.PageInvitedUsers
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Page
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{page.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PageUpdateOne is the builder for updating a single Page entity.
type PageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PageUpdateOne) SetUpdatedAt(v time.Time) *PageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *PageUpdateOne) SetTitle(v string) *PageUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableTitle(v *string) *PageUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *PageUpdateOne) SetCreatorID(v uuid.UUID) *PageUpdateOne {
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableCreatorID(v *uuid.UUID) *PageUpdateOne {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// SetInviteCode sets the "invite_code" field.
func (_u *PageUpdateOne) SetInviteCode(v string) *PageUpdateOne {
	_u.mutation.SetInviteCode(v)
	return _u
}

// SetNillableInviteCode sets the "invite_code" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableInviteCode(v *string) *PageUpdateOne {
	if v != nil {
		_u.SetInviteCode(*v)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *PageUpdateOne) SetCreator(v *User) *PageUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// AddLinkItemIDs adds the "link_items" edge to the LinkItem entity by IDs.
func (_u *PageUpdateOne) AddLinkItemIDs(ids ...uuid.UUID) *PageUpdateOne {
	_u.mutation.AddLinkItemIDs(ids...)
	return _u
}

// AddLinkItems adds the "link_items" edges to the LinkItem entity.
func (_u *PageUpdateOne) AddLinkItems(v ...*LinkItem) *PageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkItemIDs(ids...)
}

// AddInvitedUserIDs adds the "invited_users" edge to the User entity by IDs.
func (_u *PageUpdateOne) AddInvitedUserIDs(ids ...uuid.UUID) *PageUpdateOne {
	_u.mutation.AddInvitedUserIDs(ids...)
	return _u
}

// AddInvitedUsers adds the "invited_users" edges to the User entity.
func (_u *PageUpdateOne) AddInvitedUsers(v ...*User) *PageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInvitedUserIDs(ids...)
}

// Mutation returns the PageMutation object of the builder.
func (_u *PageUpdateOne) Mutation() *PageMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *PageUpdateOne) ClearCreator() *PageUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearLinkItems clears all "link_items" edges to the LinkItem entity.
func (_u *PageUpdateOne) ClearLinkItems() *PageUpdateOne {
	_u.mutation.ClearLinkItems()
	return _u
}

// RemoveLinkItemIDs removes the "link_items" edge to LinkItem entities by IDs.
func (_u *PageUpdateOne) RemoveLinkItemIDs(ids ...uuid.UUID) *PageUpdateOne {
	_u.mutation.RemoveLinkItemIDs(ids...)
	return _u
}

// RemoveLinkItems removes "link_items" edges to LinkItem entities.
func (_u *PageUpdateOne) RemoveLinkItems(v ...*LinkItem) *PageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkItemIDs(ids...)
}

// ClearInvitedUsers clears all "invited_users" edges to the User entity.
func (_u *PageUpdateOne) ClearInvitedUsers() *PageUpdateOne {
	_u.mutation.ClearInvitedUsers()
	return _u
}

// RemoveInvitedUserIDs removes the "invited_users" edge to User entities by IDs.
func (_u *PageUpdateOne) RemoveInvitedUserIDs(ids ...uuid.UUID) *PageUpdateOne {
	_u.mutation.RemoveInvitedUserIDs(ids...)
	return _u
}

// RemoveInvitedUsers removes "invited_users" edges to User entities.
func (_u *PageUpdateOne) RemoveInvitedUsers(v ...*User) *PageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInvitedUserIDs(ids...)
}

// Where appends a list predicates to the PageUpdate builder.
func (_u *PageUpdateOne) Where(ps ...predicate.Page) *PageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PageUpdateOne) Select(field string, fields ...string) *PageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Page entity.
func (_u *PageUpdateOne) Save(ctx context.Context) (*Page, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PageUpdateOne) SaveX(ctx context.Context) *Page {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := page.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PageUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := page.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Page.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InviteCode(); ok {
		if err := page.InviteCodeValidator(v); err != nil {
			return &ValidationError{Name: "invite_code", err: fmt.Errorf(`ent: validator failed for field "Page.invite_code": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Page.creator"`)
	}
	return nil
}

func (_u *PageUpdateOne) sqlSave(ctx context.Context) (_node *Page, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(page.Table, page.Columns, sqlgraph.NewFieldSpec(page.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Page.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, page.FieldID)
		for _, f := range fields {
			if !page.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != page.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(page.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(page.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.InviteCode(); ok {
		_spec.SetField(page.FieldInviteCode, field.TypeString, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.CreatorTable,
			Columns: []string{page.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Page
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.CreatorTable,
			Columns: []string{page.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Page
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinkItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   page.LinkItemsTable,
			Columns: []string{page.LinkItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkitem.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.LinkItem
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinkItemsIDs(); len(nodes) > 0 && !_u.mutation.LinkItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   page.LinkItemsTable,
			Columns: []string{page.LinkItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkitem.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.LinkItem
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinkItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   page.LinkItemsTable,
			Columns: []string{page.LinkItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkitem.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.LinkItem
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvitedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.InvitedUsersTable,
			Columns: page.InvitedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.PageInvitedUsers
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvitedUsersIDs(); len(nodes) > 0 && !_u.mutation.InvitedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.InvitedUsersTable,
			Columns: page.InvitedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.PageInvitedUsers
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvitedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.InvitedUsersTable,
			Columns: page.InvitedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.PageInvitedUsers
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Page
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Page{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{page.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
