// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/linkitem"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/page"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/schema"
	"github.com/naka-sei/tsudzuri/infrastructure/db/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	linkitemMixin := schema.LinkItem{}.Mixin()
	linkitemMixinFields0 := linkitemMixin[0].Fields()
	_ = linkitemMixinFields0
	linkitemFields := schema.LinkItem{}.Fields()
	_ = linkitemFields
	// linkitemDescCreatedAt is the schema descriptor for created_at field.
	linkitemDescCreatedAt := linkitemMixinFields0[0].Descriptor()
	// linkitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	linkitem.DefaultCreatedAt = linkitemDescCreatedAt.Default.(func() time.Time)
	// linkitemDescUpdatedAt is the schema descriptor for updated_at field.
	linkitemDescUpdatedAt := linkitemMixinFields0[1].Descriptor()
	// linkitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	linkitem.DefaultUpdatedAt = linkitemDescUpdatedAt.Default.(func() time.Time)
	// linkitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	linkitem.UpdateDefaultUpdatedAt = linkitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// linkitemDescURL is the schema descriptor for url field.
	linkitemDescURL := linkitemFields[2].Descriptor()
	// linkitem.URLValidator is a validator for the "url" field. It is called by the builders before save.
	linkitem.URLValidator = linkitemDescURL.Validators[0].(func(string) error)
	// linkitemDescPriority is the schema descriptor for priority field.
	linkitemDescPriority := linkitemFields[4].Descriptor()
	// linkitem.DefaultPriority holds the default value on creation for the priority field.
	linkitem.DefaultPriority = linkitemDescPriority.Default.(int)
	// linkitemDescID is the schema descriptor for id field.
	linkitemDescID := linkitemFields[0].Descriptor()
	// linkitem.DefaultID holds the default value on creation for the id field.
	linkitem.DefaultID = linkitemDescID.Default.(func() uuid.UUID)
	pageMixin := schema.Page{}.Mixin()
	pageMixinFields0 := pageMixin[0].Fields()
	_ = pageMixinFields0
	pageFields := schema.Page{}.Fields()
	_ = pageFields
	// pageDescCreatedAt is the schema descriptor for created_at field.
	pageDescCreatedAt := pageMixinFields0[0].Descriptor()
	// page.DefaultCreatedAt holds the default value on creation for the created_at field.
	page.DefaultCreatedAt = pageDescCreatedAt.Default.(func() time.Time)
	// pageDescUpdatedAt is the schema descriptor for updated_at field.
	pageDescUpdatedAt := pageMixinFields0[1].Descriptor()
	// page.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	page.DefaultUpdatedAt = pageDescUpdatedAt.Default.(func() time.Time)
	// page.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	page.UpdateDefaultUpdatedAt = pageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// pageDescTitle is the schema descriptor for title field.
	pageDescTitle := pageFields[1].Descriptor()
	// page.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	page.TitleValidator = func() func(string) error {
		validators := pageDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pageDescInviteCode is the schema descriptor for invite_code field.
	pageDescInviteCode := pageFields[3].Descriptor()
	// page.InviteCodeValidator is a validator for the "invite_code" field. It is called by the builders before save.
	page.InviteCodeValidator = func() func(string) error {
		validators := pageDescInviteCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(invite_code string) error {
			for _, fn := range fns {
				if err := fn(invite_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pageDescID is the schema descriptor for id field.
	pageDescID := pageFields[0].Descriptor()
	// page.DefaultID holds the default value on creation for the id field.
	page.DefaultID = pageDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUID is the schema descriptor for uid field.
	userDescUID := userFields[1].Descriptor()
	// user.UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	user.UIDValidator = userDescUID.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
