// Code generated by MockGen. DO NOT EDIT.
// Source: ./create.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_create/create.go -source=./create.go -package=mockcreateusecase
//

// Package mockcreateusecase is a generated GoMock package.
package mockcreateusecase

import (
	context "context"
	reflect "reflect"

	user "github.com/naka-sei/tsudzuri/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateUsecase is a mock of CreateUsecase interface.
type MockCreateUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUsecaseMockRecorder
	isgomock struct{}
}

// MockCreateUsecaseMockRecorder is the mock recorder for MockCreateUsecase.
type MockCreateUsecaseMockRecorder struct {
	mock *MockCreateUsecase
}

// NewMockCreateUsecase creates a new mock instance.
func NewMockCreateUsecase(ctrl *gomock.Controller) *MockCreateUsecase {
	mock := &MockCreateUsecase{ctrl: ctrl}
	mock.recorder = &MockCreateUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUsecase) EXPECT() *MockCreateUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCreateUsecase) Create(ctx context.Context, uid string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, uid)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCreateUsecaseMockRecorder) Create(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreateUsecase)(nil).Create), ctx, uid)
}
