// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/naka-sei/tsudzuri/infrastructure/db/page"
	"github.com/naka-sei/tsudzuri/infrastructure/db/postgres"
	"github.com/naka-sei/tsudzuri/infrastructure/db/user"
	"github.com/naka-sei/tsudzuri/presentation/grpc"
	page3 "github.com/naka-sei/tsudzuri/presentation/grpc/page"
	user3 "github.com/naka-sei/tsudzuri/presentation/grpc/user"
	page2 "github.com/naka-sei/tsudzuri/usecase/page"
	"github.com/naka-sei/tsudzuri/usecase/service"
	user2 "github.com/naka-sei/tsudzuri/usecase/user"
)

// Injectors from wire.go:

func InitializePresentationServer(dbConn *postgres.Connection) (*presentationgrpc.Server, error) {
	pageRepository := page.NewPageRepository(dbConn)
	transactionService := transactionServiceProvider(dbConn)
	createUsecase := page2.NewCreateUsecase(pageRepository, transactionService)
	createService := page3.NewCreateService(createUsecase)
	getUsecase := page2.NewGetUsecase(pageRepository)
	getService := page3.NewGetService(getUsecase)
	listUsecase := page2.NewListUsecase(pageRepository)
	listService := page3.NewListService(listUsecase)
	editUsecase := page2.NewEditUsecase(pageRepository, transactionService)
	editService := page3.NewEditService(editUsecase)
	deleteUsecase := page2.NewDeleteUsecase(pageRepository, transactionService)
	deleteService := page3.NewDeleteService(deleteUsecase)
	linkAddUseCase := page2.NewLinkAddUsecase(pageRepository, transactionService)
	linkAddService := page3.NewLinkAddService(linkAddUseCase)
	linkRemoveUseCase := page2.NewLinkRemoveUsecase(pageRepository, transactionService)
	linkRemoveService := page3.NewLinkRemoveService(linkRemoveUseCase)
	userRepository := user.NewUserRepository(dbConn)
	userCreateUsecase := user2.NewCreateUsecase(userRepository, transactionService)
	userCreateService := user3.NewCreateService(userCreateUsecase)
	loginUsecase := user2.NewLoginUsecase(userRepository, transactionService)
	loginService := user3.NewLoginService(loginUsecase)
	server := presentationgrpc.NewServer(createService, getService, listService, editService, deleteService, linkAddService, linkRemoveService, userCreateService, loginService)
	return server, nil
}

// wire.go:

func transactionServiceProvider(dbc *postgres.Connection) service.TransactionService {
	return dbc
}

var (
	presentationSet = wire.NewSet(page3.NewCreateService, page3.NewGetService, page3.NewListService, page3.NewEditService, page3.NewDeleteService, page3.NewLinkAddService, page3.NewLinkRemoveService, user3.NewCreateService, user3.NewLoginService, presentationgrpc.NewServer)
	usecaseSet      = wire.NewSet(page2.NewCreateUsecase, page2.NewGetUsecase, page2.NewListUsecase, page2.NewEditUsecase, page2.NewDeleteUsecase, page2.NewLinkAddUsecase, page2.NewLinkRemoveUsecase, user2.NewCreateUsecase, user2.NewLoginUsecase)
	repoSet         = wire.NewSet(page.NewPageRepository, user.NewUserRepository)
	serviceSet      = wire.NewSet(
		transactionServiceProvider,
	)
)
