// Code generated by MockGen. DO NOT EDIT.
// Source: ./edit.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_edit/edit.go -source=./edit.go -package=mockeditusecase
//

// Package mockeditusecase is a generated GoMock package.
package mockeditusecase

import (
	context "context"
	reflect "reflect"

	page "github.com/naka-sei/tsudzuri/domain/page"
	gomock "go.uber.org/mock/gomock"
)

// MockEditUsecase is a mock of EditUsecase interface.
type MockEditUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockEditUsecaseMockRecorder
	isgomock struct{}
}

// MockEditUsecaseMockRecorder is the mock recorder for MockEditUsecase.
type MockEditUsecaseMockRecorder struct {
	mock *MockEditUsecase
}

// NewMockEditUsecase creates a new mock instance.
func NewMockEditUsecase(ctrl *gomock.Controller) *MockEditUsecase {
	mock := &MockEditUsecase{ctrl: ctrl}
	mock.recorder = &MockEditUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditUsecase) EXPECT() *MockEditUsecaseMockRecorder {
	return m.recorder
}

// Edit mocks base method.
func (m *MockEditUsecase) Edit(ctx context.Context, pageID, title string, links page.Links) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", ctx, pageID, title, links)
	ret0, _ := ret[0].(error)
	return ret0
}

// Edit indicates an expected call of Edit.
func (mr *MockEditUsecaseMockRecorder) Edit(ctx, pageID, title, links any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockEditUsecase)(nil).Edit), ctx, pageID, title, links)
}
