// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// EdgeCreatedPages holds the string denoting the created_pages edge name in mutations.
	EdgeCreatedPages = "created_pages"
	// EdgeInvitedPages holds the string denoting the invited_pages edge name in mutations.
	EdgeInvitedPages = "invited_pages"
	// Table holds the table name of the user in the database.
	Table = "users"
	// CreatedPagesTable is the table that holds the created_pages relation/edge.
	CreatedPagesTable = "pages"
	// CreatedPagesInverseTable is the table name for the Page entity.
	// It exists in this package in order to avoid circular dependency with the "page" package.
	CreatedPagesInverseTable = "pages"
	// CreatedPagesColumn is the table column denoting the created_pages relation/edge.
	CreatedPagesColumn = "creator_id"
	// InvitedPagesTable is the table that holds the invited_pages relation/edge. The primary key declared below.
	InvitedPagesTable = "page_users"
	// InvitedPagesInverseTable is the table name for the Page entity.
	// It exists in this package in order to avoid circular dependency with the "page" package.
	InvitedPagesInverseTable = "pages"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUID,
	FieldProvider,
	FieldEmail,
}

var (
	// InvitedPagesPrimaryKey and InvitedPagesColumn2 are the table columns denoting the
	// primary key for the invited_pages relation (M2M).
	InvitedPagesPrimaryKey = []string{"page_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	UIDValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Provider defines the type for the "provider" enum field.
type Provider string

// ProviderAnonymous is the default value of the Provider enum.
const DefaultProvider = ProviderAnonymous

// Provider values.
const (
	ProviderAnonymous Provider = "anonymous"
	ProviderGoogle    Provider = "google"
	ProviderFacebook  Provider = "facebook"
)

func (pr Provider) String() string {
	return string(pr)
}

// ProviderValidator is a validator for the "provider" field enum values. It is called by the builders before save.
func ProviderValidator(pr Provider) error {
	switch pr {
	case ProviderAnonymous, ProviderGoogle, ProviderFacebook:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for provider field: %q", pr)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUID orders the results by the uid field.
func ByUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByCreatedPagesCount orders the results by created_pages count.
func ByCreatedPagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCreatedPagesStep(), opts...)
	}
}

// ByCreatedPages orders the results by created_pages terms.
func ByCreatedPages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedPagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInvitedPagesCount orders the results by invited_pages count.
func ByInvitedPagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInvitedPagesStep(), opts...)
	}
}

// ByInvitedPages orders the results by invited_pages terms.
func ByInvitedPages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvitedPagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCreatedPagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedPagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CreatedPagesTable, CreatedPagesColumn),
	)
}
func newInvitedPagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvitedPagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, InvitedPagesTable, InvitedPagesPrimaryKey...),
	)
}
