// Code generated by MockGen. DO NOT EDIT.
// Source: ./link_remove.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_link_remove/link_remove.go -source=./link_remove.go -package=mocklinkremoveusecase
//

// Package mocklinkremoveusecase is a generated GoMock package.
package mocklinkremoveusecase

import (
	context "context"
	reflect "reflect"

	page "github.com/naka-sei/tsudzuri/usecase/page"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkRemoveUseCase is a mock of LinkRemoveUseCase interface.
type MockLinkRemoveUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRemoveUseCaseMockRecorder
	isgomock struct{}
}

// MockLinkRemoveUseCaseMockRecorder is the mock recorder for MockLinkRemoveUseCase.
type MockLinkRemoveUseCaseMockRecorder struct {
	mock *MockLinkRemoveUseCase
}

// NewMockLinkRemoveUseCase creates a new mock instance.
func NewMockLinkRemoveUseCase(ctrl *gomock.Controller) *MockLinkRemoveUseCase {
	mock := &MockLinkRemoveUseCase{ctrl: ctrl}
	mock.recorder = &MockLinkRemoveUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRemoveUseCase) EXPECT() *MockLinkRemoveUseCaseMockRecorder {
	return m.recorder
}

// LinkRemove mocks base method.
func (m *MockLinkRemoveUseCase) LinkRemove(ctx context.Context, input page.LinkRemoveUsecaseInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkRemove", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkRemove indicates an expected call of LinkRemove.
func (mr *MockLinkRemoveUseCaseMockRecorder) LinkRemove(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkRemove", reflect.TypeOf((*MockLinkRemoveUseCase)(nil).LinkRemove), ctx, input)
}
