// Code generated by MockGen. DO NOT EDIT.
// Source: ./link_add.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_link_add/link_add.go -source=./link_add.go -package=mocklinkaddusecase
//

// Package mocklinkaddusecase is a generated GoMock package.
package mocklinkaddusecase

import (
	context "context"
	reflect "reflect"

	page "github.com/naka-sei/tsudzuri/usecase/page"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkAddUseCase is a mock of LinkAddUseCase interface.
type MockLinkAddUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLinkAddUseCaseMockRecorder
	isgomock struct{}
}

// MockLinkAddUseCaseMockRecorder is the mock recorder for MockLinkAddUseCase.
type MockLinkAddUseCaseMockRecorder struct {
	mock *MockLinkAddUseCase
}

// NewMockLinkAddUseCase creates a new mock instance.
func NewMockLinkAddUseCase(ctrl *gomock.Controller) *MockLinkAddUseCase {
	mock := &MockLinkAddUseCase{ctrl: ctrl}
	mock.recorder = &MockLinkAddUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkAddUseCase) EXPECT() *MockLinkAddUseCaseMockRecorder {
	return m.recorder
}

// LinkAdd mocks base method.
func (m *MockLinkAddUseCase) LinkAdd(ctx context.Context, input page.LinkAddUsecaseInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkAdd", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkAdd indicates an expected call of LinkAdd.
func (mr *MockLinkAddUseCaseMockRecorder) LinkAdd(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkAdd", reflect.TypeOf((*MockLinkAddUseCase)(nil).LinkAdd), ctx, input)
}
