// Code generated by MockGen. DO NOT EDIT.
// Source: ./login.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_login/login.go -source=./login.go -package=mockloginusecase
//

// Package mockloginusecase is a generated GoMock package.
package mockloginusecase

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginUsecase is a mock of LoginUsecase interface.
type MockLoginUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockLoginUsecaseMockRecorder
	isgomock struct{}
}

// MockLoginUsecaseMockRecorder is the mock recorder for MockLoginUsecase.
type MockLoginUsecaseMockRecorder struct {
	mock *MockLoginUsecase
}

// NewMockLoginUsecase creates a new mock instance.
func NewMockLoginUsecase(ctrl *gomock.Controller) *MockLoginUsecase {
	mock := &MockLoginUsecase{ctrl: ctrl}
	mock.recorder = &MockLoginUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginUsecase) EXPECT() *MockLoginUsecaseMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockLoginUsecase) Login(ctx context.Context, provider string, email *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, provider, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockLoginUsecaseMockRecorder) Login(ctx, provider, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockLoginUsecase)(nil).Login), ctx, provider, email)
}
